server:
  port: 9090

spring:
  application:
    name: api-gateway
  profiles:
    active: default
  cloud:
    gateway:
      routes:
        - id: product-catalog
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**
        - id: user-service-auth
          uri: http://localhost:8089
          predicates:
            - Path=/auth/**
        - id: user-service-users
          uri: http://localhost:8089
          predicates:
            - Path=/users/**
        - id: cart-service
          uri: http://localhost:8085
          predicates:
            - Path=/cart/**,/checkout/**
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/orders/**
        - id: payment-service
          uri: http://localhost:8765
          predicates:
            - Path=/api/payments/**

management:
  endpoints:
    web:
      exposure:
        include: health